// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yunjarkgxyxucduqtkqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1bmphcmtneHl4dWNkdXF0a3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTQ5ODUsImV4cCI6MjA1OTQzMDk4NX0.mpsAOmYrwgkOZZMxern1ljYqhtc4j80ougiTyo1ixPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);